# Generated by Django 5.2.4 on 2025-07-28 07:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='id')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='номер телефона')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название склада')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('open_time', models.TimeField(default=datetime.time(7, 0), verbose_name='open_time')),
                ('close_time', models.TimeField(default=datetime.time(19, 0), verbose_name='close_time')),
                ('total_boxes_size_s', models.PositiveIntegerField(default=0, verbose_name='боксы размера S')),
                ('total_boxes_size_m', models.PositiveIntegerField(default=0, verbose_name='боксы размера M')),
                ('total_boxes_size_l', models.PositiveIntegerField(default=0, verbose_name='боксы размера L')),
                ('available_boxes_s', models.PositiveIntegerField(default=0, verbose_name='доступные боксы S')),
                ('available_boxes_m', models.PositiveIntegerField(default=0, verbose_name='доступные боксы M')),
                ('available_boxes_l', models.PositiveIntegerField(default=0, verbose_name='доступные боксы L')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10, verbose_name='номер бокса')),
                ('size', models.CharField(choices=[('S', '1 м3'), ('M', '5 м3'), ('L', '10 м3')], max_length=2, verbose_name='размер бокса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена аренды в месяц')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступен для аренды')),
                ('start_rent_date', models.DateTimeField(blank=True, null=True, verbose_name='начало аренды')),
                ('end_rent_date', models.DateTimeField(blank=True, null=True, verbose_name='конец аренды')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='selfstorage_db.client', verbose_name='клиент')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='selfstorage_db.warehouse', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
