# Generated by Django 5.2.4 on 2025-07-28 12:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='id')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('is_legal', models.BooleanField(default=False, verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('open_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Время открытия')),
                ('close_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Время закрытия')),
                ('total_boxes', models.PositiveIntegerField(default=0, verbose_name='Общее количество ячеек')),
                ('available_boxes', models.PositiveIntegerField(default=0, verbose_name='Доступные ячейки')),
                ('total_racks', models.PositiveIntegerField(default=0, verbose_name='Количество стеллажей')),
                ('available_racks', models.PositiveIntegerField(default=0, verbose_name='Доступные стеллажи')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Номер единицы')),
                ('size', models.CharField(choices=[('S', 'Малый (1 м³)'), ('M', 'Средний (5 м³)'), ('L', 'Большой (10 м³)'), ('XL', 'Очень большой (15 м³)'), ('RACK', 'Стеллаж для документов')], max_length=5, verbose_name='Тип/размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('start_rent_date', models.DateField(blank=True, null=True, verbose_name='Начало аренды')),
                ('end_rent_date', models.DateField(blank=True, null=True, verbose_name='Окончание аренды')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_units', to='selfstorage_db.client', verbose_name='Арендатор')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='selfstorage_db.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Единица хранения',
                'verbose_name_plural': 'Единицы хранения',
                'unique_together': {('warehouse', 'unit_number')},
            },
        ),
    ]
